trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  GitCommit: $(Build.SourceVersion)

steps:
- script: yarn install --frozen-lockfile
  displayName: 'Install dependencies'

- script: yarn build
  displayName: 'Build'

- script: yarn lint
  displayName: 'Lint'

- task: DownloadSecureFile@1
  name: envFile
  displayName: 'Creating .env file'
  inputs:
    secureFile: '.env'

- task: CopyFiles@2
  displayName: 'Copying files'
  inputs:
    Contents: |
      build/**
      public/**
      package.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- script: |
    echo Copying $(envFile.secureFilePath) to $(Build.ArtifactStagingDirectory)
    cp $(envFile.secureFilePath) $(Build.ArtifactStagingDirectory)/.env
  displayName: 'Copying .env file'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'drop'
