trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  GitCommit: $(Build.SourceVersion)

steps:
- script: yarn install --frozen-lockfile
  displayName: 'Install dependencies'

- task: DownloadSecureFile@1
  name: appConfig
  displayName: 'Getting the app config file'
  inputs:
    secureFile: 'appConfig.ts'

- script: |
    echo Copying $(appConfig.secureFilePath)
    cp $(appConfig.secureFilePath) src/appConfig.ts
  displayName: 'Copying appConfig file'

- script: yarn lint
  displayName: 'Lint'

- script: yarn build
  displayName: 'Build'

- task: CopyFiles@2
  displayName: 'Copying files'
  inputs:
    Contents: |
      build/**
      public/**
      package.json
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'drop'
