trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  GitCommit: $(Build.SourceVersion)

steps:
- script: yarn install --frozen-lockfile
  displayName: 'Install dependencies'

- script: yarn build
  displayName: 'Build'

- script: yarn lint
  displayName: 'Lint'

- task: CopyFiles@2
  displayName: 'Copy files'
  inputs:
    sourceFolder: './build'
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
